# Generated by Django 5.0.6 on 2026-06-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_path', models.CharField(help_text='ej. amb.temp_c, bat.pct', max_length=100)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '==')], max_length=5)),
                ('threshold', models.FloatField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], max_length=20)),
                ('webhook_url', models.URLField(blank=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
