# Generated by Django 5.0.6 on 2026-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryreading',
            name='source_gateway',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
