# Generated by Django 5.0.6 on 2026-06-04 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('target', models.CharField(choices=[('emisor', 'Emisor'), ('receptor', 'Receptor')], max_length=20)),
                ('binary', models.FileField(upload_to='firmware/')),
                ('config_template', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('compiled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-compiled_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashed_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('usb_serial', 'USB Serial'), ('ota_wifi', 'OTA WiFi')], max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_logs', to='devices.device')),
                ('firmware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firmware.firmwarebuild')),
            ],
            options={
                'ordering': ['-flashed_at'],
            },
        ),
    ]
