# Generated by Django 5.0.6 on 2026-06-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwarebuild',
            name='build_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='firmwarebuild',
            name='status',
            field=models.CharField(choices=[('ready', 'Listo'), ('building', 'Compilando'), ('error', 'Error')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='firmwarebuild',
            name='binary',
            field=models.FileField(blank=True, null=True, upload_to='firmware/'),
        ),
    ]
