# Generated by Django 5.0.6 on 2026-06-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0002_firmwarebuild_build_log_firmwarebuild_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwarebuild',
            name='flash_offset',
            field=models.IntegerField(default=0),
        ),
    ]
