[platformio]
default_envs = emisor

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
    jgromes/RadioLib @ ^7.1.2

[env:emisor]
build_src_filter = +<emisor/>
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit SHTC3 Library @ ^1.0.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    mikalhart/TinyGPSPlus @ ^1.0.3

[env:receptor]
build_src_filter = +<receptor/>
lib_deps = ${env.lib_deps}
