# Generated by Django 5.0.6 on 2026-06-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('emisor', 'Emisor (Nodo Sensor)'), ('receptor', 'Receptor (Gateway)')], default='emisor', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('SHTC3', 'SHTC3 — Temperatura/Humedad Ambiente'), ('DS18B20', 'DS18B20 — Temperatura Sonda'), ('GPS', 'GPS — Posición'), ('BAT', 'Batería — Voltaje/Porcentaje')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
