# Generated by Django 5.0.6 on 2026-06-19 00:00

import apps.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='provisioning_token',
            field=models.CharField(default=apps.devices.models._gen_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('set_sleep', 'Cambiar intervalo de envío'), ('enable_sensor', 'Activar/desactivar sensor'), ('set_espnow_channel', 'Cambiar canal ESP-NOW'), ('restart', 'Reiniciar dispositivo'), ('set_device_id', 'Cambiar ID de dispositivo'), ('set_lora_sf', 'LoRa SF (ignorado en modo ESP-NOW)'), ('set_lora_power', 'LoRa potencia (ignorado en modo ESP-NOW)')], max_length=30),
        ),
    ]
