# Generated by Django 5.0.6 on 2026-07-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_espnow_command_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('set_sleep', 'Cambiar intervalo de envío'), ('disable_sensor', 'Desactivar sensor'), ('enable_sensor', 'Activar sensor'), ('restart', 'Reiniciar dispositivo'), ('set_lora_sf', 'Cambiar LoRa Spreading Factor'), ('set_lora_power', 'Cambiar potencia LoRa (dBm)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('SHTC3', 'SHTC3 — Temperatura/Humedad Ambiente'), ('GY39', 'GY-39 — Temperatura/Humedad/Presión (BME280, I2C)'), ('DS18B20', 'DS18B20 — Temperatura Sonda'), ('GPS', 'GPS — Posición'), ('BAT', 'Batería — Voltaje/Porcentaje')], max_length=20),
        ),
    ]
