# Generated by Django 5.0.6 on 2026-07-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_gy39_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('set_sleep', 'Cambiar intervalo de envío'), ('enable_sensor', 'Activar/desactivar sensor'), ('set_device_id', 'Cambiar ID de dispositivo'), ('restart', 'Reiniciar dispositivo')], max_length=30),
        ),
    ]
