# Generated by Django 5.0.6 on 2026-07-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_radiolib_command_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('SHTC3', 'SHTC3 — Temperatura/Humedad Ambiente (incl. placas GY-39)'), ('DS18B20', 'DS18B20 — Temperatura Sonda'), ('GPS', 'GPS — Posición'), ('BAT', 'Batería — Voltaje/Porcentaje')], max_length=20),
        ),
    ]
